export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SET_ITEM_COUNT = "SET_ITEM_COUNT";

export const CHANGE_THEME = "CHANGE_THEME";

export const UNLOCK_TASK = "UNLOCK_TASK";
export const MODIFY_UNLOCKED_TASK = "MODIFY_UNLOCKED_TASK";
export const MODIFY_ALL_UNLOCKED_TASKS = "MODIFY_ALL_UNLOCKED_TASKS";
export const COMPLETE_TASK = "COMPLETE_TASK";
export const CHANGE_TAB = "CHANGE_TAB";
